version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo Installing dependencies...
      - dotnet restore

  pre_build:
    commands:
      - echo Starting pre-build phase...
      - dotnet --version

  build:
    commands:
      - echo Building the application...
      - dotnet build --configuration Release
      - echo Publishing the application...
      - dotnet publish -c Release -o ./publish

  post_build:
    commands:
      - echo Packaging application for Elastic Beanstalk...
      - cd publish
      - zip -r ../deployment.zip *
      - cd ..
      - echo "Creating Procfile if not exists..."
      - echo "web: dotnet backHrManagement.dll" > Procfile
      - zip -r deployment.zip Procfile
      - echo Creating manifest file...
      - echo '{"manifestVersion":1,"deployments":{"aspNetCoreWeb":[{"name":"app","parameters":{"appBundle":"deployment.zip","iisPath":"/","iisWebSite":"Default Web Site"}}]}}' > aws-windows-deployment-manifest.json
      - zip -r deployment.zip aws-windows-deployment-manifest.json
      - echo Build completed on `date`

artifacts:
  files:
    - deployment.zip
    - aws-windows-deployment-manifest.json
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - '/root/.nuget/**/*'
