version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  build:
    commands:
      - dotnet publish -c Release -o ./app
      - zip -r deployment.zip ./app

artifacts:
  files:
    - deployment.zip
