version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  build:
    commands:
      - echo "Running dotnet publish..."
      - dotnet publish -c Release -o publish
      - cd publish
      - zip -r ../deployment.zip .
artifacts:
  files:
    - deployment.zip
