version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing .NET 9.0.102..."
      - wget https://dot.net/v1/dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --version 9.0.102 --install-dir /root/.dotnet
      - export PATH=/root/.dotnet:$PATH
      - export DOTNET_ROOT=/root/.dotnet
      - dotnet --version
  
  build:
    commands:
      - echo "Running dotnet restore..."
      - dotnet restore
      - echo "Running dotnet publish..."
      - dotnet publish -c Release -o publish
      - cd publish
      - zip -r ../deployment.zip .
      - cd ..
      - echo "Deployment package created successfully"

artifacts:
  files:
    - deployment.zip
  discard-paths: no

cache:
  paths:
    - '/root/.dotnet/**/*'
    - '/root/.nuget/**/*'
