version: 0.2

phases:
  install:
    commands:
      - echo "🔧 Installing .NET 9 SDK..."
      - curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --version 9.0.100-preview.3
      - export DOTNET_ROOT=$HOME/.dotnet
      - export PATH=$DOTNET_ROOT:$PATH
      - dotnet --version

  build:
    commands:
      - echo "🚀 Building the .NET project..."
      - dotnet build Back-HR.sln --configuration Release

artifacts:
  files:
    - '**/bin/Release/**/*'
  base-directory: .
