version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6
  build:
    commands:
      - echo "Restoring packages..."
      - dotnet restore
      - echo "Building solution..."
      - dotnet build -c Release
      - echo "Publishing project..."
      - dotnet publish -c Release -o publish
      - echo "Zipping published output..."
      - cd publish
      - zip -r ../deployment.zip .
artifacts:
  files:
    - deployment.zip
